== Defining a JMS Listener

You can define a listener using any the following syntax

[source,java]
----
@JMSListener("myConnectionFactory")
public class MyListener {
    @Queue("my-queue")
    public void receive(@Body String message) {
        // do logic
    }

    @Topic("my-topic")
    public void onMessage(@Body MyTopicDto dto, @Header(JMSHeaders.JMS_CORRELATION_ID) String correlationId) {
        // topic logic
    }

    @Queue(
        destination = "my-other-queue",
        concurrency = "1-5",
        transacted = true,
        acknowledgement = Session.CLIENT_ACKNOWLEDGE)
    public void handle(@Body String message, @Header("X-Arbitrary-Header") String myHeader) {
        // other queue logic
    }

    @Queue(
        destination = "another-queue",
        executor = "my-executor-service")
    public void go(@Body String message) {
        // logic
    }
}

@Data
class MyTopicDto {
    private String id;
    private Integer counter;
    private Date date;
    private Map<String, String> metadata;
}
----

Some key notes here:

1. Your class must be annotated with `@JMSListener`.
This defines it as a bean and enables the post-processing logic
2. The value of the `@JMSListener` must correspond with the value of exactly one `@JMSConnectionFactory` annotated bean in the `BeanContext`.
If there is no `@JMSConnectionFactory` with the same value, or if there is more than one then you will receive an `IllegalStateException`
3. There must be at least one method annotated with either `@Queue`
or `@Topic` in an `@JMSListener` class.
If there is not, an `IllegalStateException`
will be thrown
4. Any method annotated with `@Queue` or `@Topic` must have one parameter which is annotated with `@Body`.
All other parameters must have the `@Header` annotation.
5. If you want to use a Micronaut managed executor service, you can specify it by name in the `executor` parameter of the `@Queue` or `@Topic` annotations.
Or if you would like a dedicated `ExecutorService` you can specify the `concurrency`
parameter (in the form `"x-y"`) which will manage a `ThreadPool` with an initial size of `x`
and a maximum size of `y`.
