= Getting Started

To add support for JMS, introduce the following dependency to your project

dependency:io.micronaut.jms:micronaut-jms-core[]

If you are using a supported message broker (currently only ActiveMQ)
then you will need to add the following properties to your `application.yml`

[source,yaml]
----
micronaut:
  jms:
    activemq:
      enabled: true
      connection-string: 'tcp://host:61616'
----

and the following to your `build.gradle` or `pom.xml`

dependency:io.micronaut.jms:micronaut-jms-activemq[]

If your message broker is not supported, then you must provide
the `ConnectionFactory` manually to the `BeanContext`
in the following manner:

[source,java]
----
@Factory
public class JMSConfig {
    @JMSConnectionFactory("myConnectionFactory")
    public ConnectionFactory connFactory() {
        return new ActiveMqConnectionFactory("tcp://host:616161");
    }
}
----

Once you have these changes in place, you can start defining listeners and producers.

== Defining a JMS Producer

You can define a producer using the following syntax

[source,java]
----
@JMSProducer("myConnectionFactory")
public interface MyProducer {
    @Queue(destination = "my-queue")
    void send(MyObject message, @Header("X-Arbitrary-Header") String arbitraryHeader);
}
----

Additionally, a `JMSProducer` can be instantiated directly and requires minimal configuration to get up and running.
The following snippet should suffice:

[source,java]
----
@Factory
public class MyConfiguration {
    @Singleton
    public JmsProducer producer(
        JMSConnectionPool pool) {
        final JmsProducer producer = new JmsProducer();
        producer.setConnectionFactory(pool);
        producer.setSerializer(new DefaultSerializerDeserializer());
        return producer;
    }
}

@Singleton
public class MyBusinessLogic {

    @Inject
    private JmsProducer producer;

    public void aMethod(String message) {
        producer.send("my-queue", message, new MessageHeader(JMSHeaders.JMS_REPLY_TO, "my-reply-queue"));
    }

    public <T> void anotherMethod(T complexMessage) {
        producer.send("my-queue", complexMessage, new MessageHeader("X-Arbitrary-Header", "my-reply-queue"));
    }
}
----

_**NOTE**_: If you pass an object to the `send` method then by default
it will be serialized to JSON and sent to the broker as a `javax.jms.TextMessage`
