plugins {
    id 'io.micronaut.build.internal.jms-base'
    id 'io.micronaut.build.internal.module'
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
ossIndexAudit {
if (sonatypePluginConfigured) {
    username = ossIndexUsername
    password = ossIndexPassword
}
    excludeCompileOnly = true
    excludeCoordinates = ["commons-beanutils:commons-beanutils:1.10.1"]
}

dependencies {
    compileOnly libs.jsr305 // for "warning: unknown enum constant When.MAYBE"
    runtimeOnly(libs.javax.json.api)
}

