plugins {
    id 'groovy'
    id 'io.micronaut.build.internal.jms-application'
}

micronaut {
    importMicronautPlatform = false
    testRuntime "junit5"
}
dependencies {
    micronautBoms(platform(mn.micronaut.core.bom))
    micronautBoms(platform(mnLogging.micronaut.logging.bom))
    micronautBoms(platform(mnTest.micronaut.test.bom))
    testImplementation mnTest.micronaut.test.core
    testImplementation mn.micronaut.http.client
}
