plugins {
    id 'io.micronaut.build.internal.jms-base'
    id 'io.micronaut.build.internal.module'
}

ossIndexAudit {
    excludeCompileOnly = true
    excludeCoordinates = ["commons-beanutils:commons-beanutils:1.10.1"]
}

dependencies {
    compileOnly libs.jsr305 // for "warning: unknown enum constant When.MAYBE"
    runtimeOnly(libs.javax.json.api)
}

//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-groovy-5.0")
    }
}
